name: flutter_msal_mobile
description: A new Flutter plugin project.
version: 1.0.0
homepage: https://example.com

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_msal_mobile
        pluginClass: FlutterMsalMobilePlugin
