name: flutter_msal_mobile
description: A Flutter package for integrating MSAL-based mobile authentication, designed for secure and efficient user identity management in enterprise and business applications.
version: 1.0.2+1
repository: https://github.com/celvinren/flutter_msal_mobile
issue_tracker: https://github.com/celvinren/flutter_msal_mobile/issues

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_msal_mobile
        pluginClass: FlutterMsalMobilePlugin
      ios:
        pluginClass: FlutterMsalMobilePlugin
