name: flutter_msal_mobile
description: Flutter plugin project for MSAL mobile.
version: 1.0.0
homepage: https://calvinr.com
repository: https://github.com/celvinren/flutter_msal_mobile
issue_tracker: https://github.com/celvinren/flutter_msal_mobile/issues

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_msal_mobile
        pluginClass: FlutterMsalMobilePlugin
      ios:
        pluginClass: FlutterMsalMobilePlugin
